// works as index.js as in create-react-app
import './globals.css'
import Head from 'next/head'

export const metadata = {
  title: 'Priyanshi Agrawal | Portfolio',
  description: 'Generated by create next app',
}

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <Head>
			<link rel="icon" href="/favicon.ico" sizes="any" />
		</Head>
      <body>{children}</body>
    </html>
  )
}
